name: CI/CD Pipeline - Deploy to Azure ACI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout kode dari repository
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Login ke Azure Container Registry (ACR)
      # Marketplace: https://github.com/marketplace/actions/azure-container-registry-login
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_URL }}
          username: acrlandingpagekota301
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 3: Build dan Push Docker Image ke ACR
      # Marketplace: https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/repo-landingpage-kota301:${{ github.sha }}

      # Step 4: Login ke Azure menggunakan username & password
      # Marketplace: https://github.com/marketplace/actions/azure-login
      - name: Login to Azure
        run: |
          az login --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 5: Deploy image terbaru ke Azure Container Instance
      # Marketplace: https://github.com/marketplace/actions/deploy-to-azure-container-instances
      - name: Deploy to ACI
        uses: azure/aci-deploy@v1
        with:
          resource-group: rg-lab-docker
          dns-name-label: landingpage-kota301
          image: ${{ secrets.REGISTRY_URL }}/repo-landingpage-kota301:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_URL }}
          registry-username: acrlandingpagekota301
          registry-password: ${{ secrets.ACR_PASSWORD }}
          name: ${{ secrets.SERVICE_NAME }}
          location: southeastasia
          ports: 80
          os-type: Linux
          cpu: 1
          memory: 1